# Site
repository: violetbeach/violetbeach.github.io

# Personal info
name: 이재헌
title: 카카오페이 서버 개발자
email: ti6419@gmail.com
website: https://jaehoney.tistory.com

# Additional icon links
additional_links:
  - title: Tech Blog
    icon: fab fa-blogger
    url: https://jaehoney.tistory.com

# Social links
github_username: violetbeach

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java, Spring 기반 3년차 개발자로써, 16만 고객사와 MAU 70만 그룹웨어의 메일 서비스 전반을 담당했고,
  현재 **카카오페이 금융 서비스 플랫폼 파트**에서 **카드 결제 서비스**를 개발하고 있습니다.  \
  성능 모니터링을 위해 Intellij Profiler, Apache JMeter, Prometheus와 같은 도구를 사용하며, 
  기존 코드와 아키텍처의 문제를 파악 후 개선하여 메모리 사용량을 감소시키고 지연 시간을 최소화하여 TPS를 증가시키는 등
  <mark>사용자 경험(UX)</mark>을 향상시키는 데 주력했습니다. \
  **높은 품질의 코드와 철저한 테스트, 확장성 있는 시스템 설계**를 위해 정리한 문서를 기반으로 팀원들과 함께 해결 방안을 고민하며,
  마주한 문제는 자세한 학습과 더 좋은 방법 도출을 위해 블로그에 <mark>상세히 기록</mark>하고 있습니다. \
  발생한 이슈의 원인과 해결한 결과를 예상과 추측을 넘어 **반드시 데이터로 확인하는 것을 지향**합니다.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag